# Generated by Django 4.0.4 on 2022-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('Days', 'Days'), ('Month', 'Month'), ('Year', 'Year')], max_length=100, null=True),
        ),
    ]
