# Generated by Django 4.0.4 on 2022-05-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member_duration_member_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('1', 'Days'), ('2', 'Week'), ('3', 'Month'), ('4', 'Year')], max_length=100, null=True),
        ),
    ]
