# Generated by Django 4.0.4 on 2022-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_member_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('Days', 'Days'), ('Week', 'Week'), ('Month', 'Month'), ('year', 'Year')], max_length=100, null=True),
        ),
    ]
