# Generated by Django 4.0.4 on 2022-07-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_member_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='home.category'),
        ),
    ]
